version: '3.8'
services:
  vpn-merger:
    build: .
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./output:/app/output
      - ./config:/app/config
    environment:
      - VPN_MERGER_MONITORING__ENABLE_DASHBOARD=true
      - VPN_MERGER_MONITORING__ENABLE_METRICS=true
      - DASHBOARD_TOKEN=${DASHBOARD_TOKEN:-}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 5s
      retries: 3


