site_name: CleanConfigs SubMerger
site_description: Production-grade VPN subscription aggregator
theme:
  name: material
  features:
    - navigation.sections
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
    logo: material/rocket
repo_url: https://github.com/AmirrezaFarnamTaheri/CleanConfigs-SubMerger-
nav:
  - Home: index.md
  - Quick Start: quick-start.md
  - API:
    - REST (OpenAPI): api/index.md
    - OpenAPI (Redoc): api/openapi.md
    - GraphQL: api/graphql.md
  - Deployment: deployment.md
  - Architecture: architecture.md
  - Troubleshooting: troubleshooting.md
  - Python SDK: sdk-python.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
  - redoc:
      spec-url: api/openapi.yaml
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
