[tool.black]
line-length = 100
target-version = ["py310", "py311", "py312"]

[tool.isort]
profile = "black"

[tool.ruff]
line-length = 100
select = ["E","F","I","B","UP","RUF"]
ignore = [
  # Too aggressive for this codebase at the moment
  "E501",
]

