version: "3.8"
services:
  free-nodes-api:
    build: .
    container_name: free_nodes_api
    environment:
      - DB_URL=sqlite+aiosqlite:///./data/free-nodes.db
      - RATE_LIMIT_RPM=180
      - HEALTH_CONCURRENCY=80
      - REFRESH_EVERY_MIN=20
      - CORS_ORIGINS=*
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
