apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpn-merger
  namespace: vpn-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vpn-merger
  template:
    metadata:
      labels:
        app: vpn-merger
    spec:
      containers:
      - name: merger
        image: vpn-merger:latest
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        env:
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: vpn-merger-secrets
              key: redis-url
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: vpn-merger-secrets
              key: api-token
        - name: OUTPUT_DIR
          value: "/data"
        ports:
        - containerPort: 8000
          name: api
        - containerPort: 8001
          name: metrics
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/ready
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: vpn-merger-service
  namespace: vpn-system
spec:
  selector:
    app: vpn-merger
  ports:
  - port: 80
    targetPort: 8000
    name: api
  - port: 8001
    targetPort: 8001
    name: metrics
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vpn-merger-hpa
  namespace: vpn-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vpn-merger
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
