version: "2.0"
metadata:
  last_updated: "2024-12-29"
  total_sources: 500
  categories: 12
  maintainer: "vpn-merger-team"
  update_frequency: "hourly"

sources:
  tier_1_premium:
    update_frequency: "hourly"
    reliability_score: 0.95
    urls:
      - url: "https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/sub_merge_base64.txt"
        format: "base64"
        protocols: ["vmess", "vless", "trojan", "ss"]
        average_configs: 5000
        last_verified: "2024-12-29"
        region: "global"
        priority: 1
      
      - url: "https://raw.githubusercontent.com/yebekhe/TelegramV2rayCollector/main/sub/mix"
        format: "mixed"
        protocols: ["all"]
        average_configs: 8000
        last_verified: "2024-12-29"
        region: "global"
        priority: 1
      
      - url: "https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml"
        format: "clash"
        protocols: ["vmess", "vless", "trojan", "ss"]
        average_configs: 3000
        last_verified: "2024-12-29"
        region: "global"
        priority: 1
      
      - url: "https://raw.githubusercontent.com/roosterkid/openproxylist/main/V2RAY.txt"
        format: "raw"
        protocols: ["vmess", "vless"]
        average_configs: 2500
        last_verified: "2024-12-29"
        region: "global"
        priority: 1
      
      - url: "https://raw.githubusercontent.com/AzadNetCH/Clash/main/AzadNet.txt"
        format: "clash"
        protocols: ["vmess", "vless", "trojan"]
        average_configs: 4000
        last_verified: "2024-12-29"
        region: "global"
        priority: 1

  tier_2_reliable:
    update_frequency: "6_hours"
    reliability_score: 0.85
    urls:
      - url: "https://raw.githubusercontent.com/mfuu/v2ray/master/v2ray"
        format: "raw"
        protocols: ["vmess", "vless"]
        average_configs: 3000
        last_verified: "2024-12-29"
        region: "global"
        priority: 2
      
      - url: "https://raw.githubusercontent.com/barry-far/V2ray-Config/main/configs.txt"
        format: "raw"
        protocols: ["vmess", "vless", "trojan"]
        average_configs: 2000
        last_verified: "2024-12-29"
        region: "global"
        priority: 2
      
      - url: "https://raw.githubusercontent.com/M-Mashreghi/Free-V2ray-Collector/main/sub/mix.txt"
        format: "mixed"
        protocols: ["vmess", "vless", "trojan", "ss"]
        average_configs: 3500
        last_verified: "2024-12-29"
        region: "global"
        priority: 2
      
      - url: "https://raw.githubusercontent.com/MatinGhanbari/v2ray-configs/main/configs.txt"
        format: "raw"
        protocols: ["vmess", "vless"]
        average_configs: 2800
        last_verified: "2024-12-29"
        region: "global"
        priority: 2
      
      - url: "https://raw.githubusercontent.com/Epodonios/v2ray-configs/main/sub_mixed.txt"
        format: "mixed"
        protocols: ["vmess", "vless", "trojan"]
        average_configs: 3200
        last_verified: "2024-12-29"
        region: "global"
        priority: 2

  specialized_protocols:
    reality:
      - url: "https://raw.githubusercontent.com/ALIILAPRO/v2rayNG-Config/main/reality.txt"
        format: "raw"
        protocols: ["vless"]
        average_configs: 1500
        last_verified: "2024-12-29"
        region: "global"
        priority: 1
      
      - url: "https://raw.githubusercontent.com/blackmatrix67/ios_rule_script/master/rule/Clash/Reality/Reality.yaml"
        format: "clash"
        protocols: ["vless"]
        average_configs: 800
        last_verified: "2024-12-29"
        region: "global"
        priority: 2
    
    hysteria2:
      - url: "https://raw.githubusercontent.com/Surfboardv2ray/Hysteria2/main/configs.txt"
        format: "raw"
        protocols: ["hysteria2"]
        average_configs: 1200
        last_verified: "2024-12-29"
        region: "global"
        priority: 1
      
      - url: "https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/hysteria2.txt"
        format: "raw"
        protocols: ["hysteria2"]
        average_configs: 900
        last_verified: "2024-12-29"
        region: "global"
        priority: 2

  regional_optimized:
    north_america:
      - url: "https://raw.githubusercontent.com/vpei/Free-Node-Merge/main/out/node.txt"
        format: "raw"
        protocols: ["vmess", "vless", "trojan"]
        average_configs: 2000
        last_verified: "2024-12-29"
        region: "US"
        priority: 1
      
      - url: "https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.txt"
        format: "raw"
        protocols: ["vmess", "vless"]
        average_configs: 1800
        last_verified: "2024-12-29"
        region: "US"
        priority: 2
    
    europe:
      - url: "https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/europe.txt"
        format: "raw"
        protocols: ["vmess", "vless", "trojan"]
        average_configs: 1600
        last_verified: "2024-12-29"
        region: "EU"
        priority: 1
    
    asia:
      - url: "https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/asia.txt"
        format: "raw"
        protocols: ["vmess", "vless", "trojan"]
        average_configs: 1400
        last_verified: "2024-12-29"
        region: "AS"
        priority: 1

  monitoring:
    health_check_interval: 3600
    failure_threshold: 3
    auto_disable: true
    notification_webhook: "${WEBHOOK_URL}"
    metrics_endpoint: "/metrics"
    alert_channels:
      - type: "webhook"
        url: "${ALERT_WEBHOOK}"
      - type: "email"
        recipients: ["${ALERT_EMAIL}"]
      - type: "slack"
        channel: "${SLACK_CHANNEL}"

  fallback_sources:
    emergency_backup:
      - url: "https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/sub_merge_base64.txt"
        format: "base64"
        protocols: ["all"]
        average_configs: 5000
        last_verified: "2024-12-29"
        region: "global"
        priority: 0  # Highest priority for fallback
