apiVersion: v1
kind: ConfigMap
metadata:
  name: streamline-config
  namespace: streamline-vpn
data:
  settings.yaml: |
    environment: production
    log_level: INFO
    cache:
      redis_url: redis://redis-service:6379/0
    database:
      postgres_url: postgresql://streamline:password@postgres-service:5432/streamline
    monitoring:
      prometheus_enabled: true
      metrics_port: 9090
