apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamline-deployment
  namespace: streamline-vpn
  labels:
    app: streamline
spec:
  replicas: 3
  selector:
    matchLabels:
      app: streamline
  template:
    metadata:
      labels:
        app: streamline
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: streamline
        image: streamline-vpn:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 8001
          name: websocket
        - containerPort: 8080
          name: config-generator
        - containerPort: 9000
          name: static-files
        env:
        - name: STREAMLINE_ENV
          value: "production"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: config
          mountPath: /app/config
        - name: data
          mountPath: /app/data
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: config
        configMap:
          name: streamline-config
      - name: data
        persistentVolumeClaim:
          claimName: streamline-pvc
