name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.10', '3.11']
    steps:
      - uses: actions/checkout@v4
      - name: Start Redis (Linux only)
        if: runner.os == 'Linux'
        run: |
          docker compose -f docker-compose.redis.yml up -d
          for i in {1..30}; do
            if docker ps --filter "health=healthy" --format '{{.Names}}' | grep -q 'redis'; then
              break
            fi
            sleep 2
          done
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r tests/requirements.txt || true
      - name: Run tests
        env:
          REDIS_URL: ${{ runner.os == 'Linux' && 'redis://localhost:6379/0' || '' }}
        run: |
          pytest -q

  docs:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install mkdocs
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocstrings mkdocs-redoc-plugin
      - name: Build docs
        run: mkdocs build
      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site

  gh-pages:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: docs
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install mkdocs
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocstrings mkdocs-redoc-plugin
      - name: Build docs
        run: mkdocs build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site

