name: tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt; fi
      - name: Run tests with coverage gate
        env:
          SKIP_NETWORK: '1'
          SKIP_DISCOVERY: '1'
        run: |
          pytest -q --cov=vpn_merger --cov-report=term-missing --cov-fail-under=90
      - name: Generate coverage badge
        if: always()
        run: |
          pip install coverage-badge
          coverage-badge -o coverage.svg -f || true
      - name: Upload coverage badge artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badge
          path: coverage.svg
